import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { Caveat } from "next/font/google";

const caveat = Caveat({
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Antje-k",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`relative w-full min-h-screen ${caveat.className}`}>
                <div className="fixed top-0 left-0 w-full h-screen bcg" />

                <Navbar />
                
                {children}
            </body>
        </html>
    );
}
